name: GitHub Action Submodule Network
description: Automatically updates the app parents of each subsidiary when the core is updated
author: Juan David Argüello Plata, jdarguello

inputs:
  platform:
    description: either 'GitHub' or 'Azure'
    required: false
    default: GitHub
  subsidiary_repo_url:
    description: 'GitHub: owner/repo  -  Azure: https://... '
    required: true
  subsidiary_token:
    description: token (from GitHub or Azure) to update the submodule
    required: true
  subsidiary_repo_username:
    description: (Only required for Azure Repos) username for the checkout process
    required: false
    default: ''
  branch:
    description: branch of the submodule
    required: false
    default: main
  

runs:
  using: 'composite'
  steps:
    - name: Update subsidiary - GitHub
      if: inputs.platform == 'GitHub'
      uses: PaulRitter/github-action-create-commit-parent-submodule@v1
      with:
        github_token: ${{ inputs.subsidiary_token }}
        parent_repository: ${{ inputs.subsidiary_repo_url }}
        parent_branch: ${{ inputs.branch }}
    - name: Checkout subsidiary - Azure
      if: inputs.platform == 'Azure'
      uses: bancolombia/checkout-azure-repo@v1
      with: 
        token: ${{ inputs.subsidiary_token }}
        username: john_doe
        password: etc
      
