name: Testing
on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - plataforma: GitHub
            filial: Bancolombia
            repo_url: jdarguello/Valko-banistmo-Azure
            rama: BANCOLOMBIA_BRANCH
          - plataforma: Azure
            filial: Banistmo
            repo_url: BANISTMO_URL
            rama: BANISTMO_BRANCH
    steps:
    - uses: actions/checkout@v2
    - name: run action
      id: run_action
      uses: ./
      with: 
        repos: ${{ matrix }}

